github: reconsumeralization@gmail.com
open_collective: your_OpenCollective_username
ko_fi: your_KoFi_username
tidelift: npm/your_Tidelift_package
community_bridge: your_CommunityBridge_project
liberapay: your_Liberapay_username
issuehunt: your_IssueHunt_username
otechie: your_Otechie_username
lfx_crowdfunding: your_LFX_Crowdfunding_project
custom: ['your_custom_url1', 'your_custom_url2']
