apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacherstudentparentadminai-deployment
  labels:
    app: teacherstudentparentadminai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: teacherstudentparentadminai
  template:
    metadata:
      labels:
        app: teacherstudentparentadminai
    spec:
      containers:
      - name: teacherstudentparentadminai
        image: teacherstudentparentadminai:latest
        ports:
        - containerPort: 5000
        env:
        - name: NAME
          value: "TeacherStudentParentAdminAi"
---
apiVersion: v1
kind: Service
metadata:
  name: teacherstudentparentadminai-service
spec:
  selector:
    app: teacherstudentparentadminai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
